
# Generated by Django 2.2.3 on 2020-01-18 06:34
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.IntegerField(default=0)),
                ('name', models.CharField(default=None, max_length=50)),
                ('pic', models.ImageField(default=None, upload_to='')),
                ('designation', models.CharField(default=None, max_length=50)),
                ('email', models.EmailField(default=None, max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
