# Generated by Django 3.0.3 on 2020-02-13 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='batch',
            new_name='year',
        ),
    ]
