# Generated by Django 3.0.3 on 2020-02-13 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='t_id',
        ),
    ]
