# Generated by Django 2.2.3 on 2020-01-18 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_id', models.IntegerField(default=0)),
                ('batch', models.IntegerField(default=0)),
                ('branch', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_id', models.IntegerField(default=0)),
                ('sem', models.IntegerField(default=0)),
                ('subject', models.CharField(default=None, max_length=50)),
                ('credit', models.IntegerField(default=0)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Batch')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_id', models.IntegerField(default=0)),
                ('pic', models.ImageField(default=None, upload_to='')),
                ('name', models.CharField(default=None, max_length=50)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Batch')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=0)),
                ('hour', models.IntegerField(default=0)),
                ('is_present', models.BooleanField(default=False)),
                ('stud_reg_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Student')),
                ('sub_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Subject')),
            ],
        ),
    ]
