# Generated by Django 2.2.3 on 2020-01-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='stud_reg_no',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='sub_id',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='branch_id',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='pic',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='branch_id',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='teacher_id',
            new_name='teacher',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='branch_id',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='sub_id',
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(default='', max_length=6),
        ),
    ]
