# Generated by Django 3.0.3 on 2020-02-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20200213_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='face_encodings',
            field=models.BinaryField(null=True),
        ),
    ]
