# Generated by Django 3.0.3 on 2020-02-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_student_face_encodings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=None)),
                ('capture_image', models.ImageField(default=None, upload_to='')),
            ],
        ),
    ]
