# Generated by Django 3.0.3 on 2020-02-13 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_attendanceimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AttendanceImage',
            new_name='AttendanceCaptureProof',
        ),
    ]
